version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_quarkus
    image: postgres:12.2
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5432:5432"